apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec:
  template:
    metadata:
      labels:
        name: nginx-ingress
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      containers:
         - name: nginx-ingress-controller
           image: nginx/nginx-ingress:edge
       args:
         - /nginx-ingress-controller
         - --configmap=$(POD_NAMESPACE)/nginx-configuration
         - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
       env:
         - name: POD_NAME
           valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
         - name: POD_NAMESPACE
           valueFrom:
             fieldRef:
               fieldPath: metadata.namesapce
       ports:
         - name: http
           containerPort: 80
         - name: https
           containerPort: 443
  replicas: 1
  selector:
    matchLabels:
      name: nginx-ingress